version: "3"

services:
    server:
        image: todobackend:v6
        ports:
            - '3001:3001'
        depends_on:
            - db


    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: todo
        ports:
            - '5433:5432'

        
