version: "3"

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        image: 'todo'
        depends_on:
            - db


    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: todo
        ports:
            - '5433:5432'
        volumes: 
            - db:/var/lib/postgresql/data
volumes:
        db:

        
